# this file contains user-facing config settings;
# internal application settings in .appsettings.yaml

# logzero log level: CRITICAL (less messages), ERROR, WARNING, INFO, DEBUG (more messages)
loglevel: INFO

# runtime settings
runtime:
  name: pyruntime
  uuid: # leave blank to generate a new uuid; or set a fixed uuid value
  reg_attempts: 0 # 0 = infinite
  reg_timeout_seconds: 5
  max_nmodules: 100
  realm: realm

# mqtt username and password in .secrets.yaml
mqtt:
  host: defined-in-compose-file
  port: defined-in-compose-file
  ssl: true

# where/how we keep program files;
# these might change, depending on class defined in .appsettings.yaml
repository:
  url: https://arena-dev1.conix.io/store

# launcher config; what starts modules
launcher:
  # launcher general settings
  pipe_stdout: true