# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Influxdb
    orgId: 1

datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  orgId: 1
  uid: metrics_db
  url: http://influxdb:8086
  basicAuth: false
  isDefault: true
  secureJsonData:
    token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
  jsonData:
    defaultBucket: "metrics"
    httpMode: "POST"
    organization: "silverline"
    version: "Flux"
  # <bool> allow users to edit datasources from the UI.
  editable: false
